[workspace]
authors = ["adiezsanchez <adiez.biotech@gmail.com>"]
channels = ["pytorch", "nvidia", "conda-forge"]
name = "hcs_cellpose_pixi_test"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
_libavif_api = "1.3.0.*"
alabaster = "1.0.0.*"
annotated-types = "0.7.0.*"
aom = "3.9.1.*"
apoc-backend = "0.12.0.*"
app-model = "0.4.0.*"
appdirs = "1.4.4.*"
asciitree = "0.3.3.*"
asttokens = "3.0.0.*"
attrs = "25.3.0.*"
aws-c-auth = "0.9.0.*"
aws-c-cal = "0.9.2.*"
aws-c-common = "0.12.4.*"
aws-c-compression = "0.3.1.*"
aws-c-event-stream = "0.5.5.*"
aws-c-http = "0.10.4.*"
aws-c-io = "0.21.2.*"
aws-c-mqtt = "0.13.3.*"
aws-c-s3 = "0.8.6.*"
aws-c-sdkutils = "0.2.4.*"
aws-checksums = "0.2.7.*"
aws-crt-cpp = "0.33.1.*"
aws-sdk-cpp = "1.11.606.*"
babel = "2.17.0.*"
bermuda = "0.1.6.*"
blas = "1.0.*"
blosc = "1.21.6.*"
bokeh = "3.8.0.*"
brotli = "1.1.0.*"
brotli-bin = "1.1.0.*"
brotli-python = "1.1.0.*"
bzip2 = "1.0.8.*"
c-ares = "1.34.5.*"
c-blosc2 = "2.19.1.*"
ca-certificates = "2025.8.3.*"
cachey = "0.2.1.*"
cairo = "1.18.4.*"
cccl = "2.8.2.*"
cellpose = "4.0.6.*"
certifi = "2025.8.3.*"
cffi = "1.17.1.*"
charls = "2.4.2.*"
charset-normalizer = "3.4.3.*"
choreographer = "1.0.10.*"
click = "8.2.1.*"
click-default-group = "1.2.4.*"
cloudpickle = "3.1.1.*"
colorama = "0.4.6.*"
coloredlogs = "15.0.1.*"
comm = "0.2.3.*"
contourpy = "1.3.2.*"
cpython = "3.10.18.*"
cuda-cccl = "12.9.27.*"
cuda-cccl_win-64 = "12.9.27.*"
cuda-cudart = "12.1.105.*"
cuda-cudart-dev = "12.1.105.*"
cuda-cupti = "12.1.105.*"
cuda-libraries = "12.1.0.*"
cuda-libraries-dev = "12.1.0.*"
cuda-nvrtc = "12.1.105.*"
cuda-nvrtc-dev = "12.1.105.*"
cuda-nvtx = "12.1.105.*"
cuda-opencl = "12.9.19.*"
cuda-opencl-dev = "12.9.19.*"
cuda-profiler-api = "12.9.79.*"
cuda-runtime = "12.1.0.*"
cuda-version = "12.9.*"
cycler = "0.12.1.*"
cytoolz = "1.0.1.*"
dask = "2025.7.0.*"
dask-core = "2025.7.0.*"
dask-image = "2024.5.3.*"
dav1d = "1.2.1.*"
debugpy = "1.8.16.*"
decorator = "5.2.1.*"
distributed = "2025.7.0.*"
docformatter = "1.7.7.*"
docstring_parser = "0.17.0.*"
docutils = "0.21.2.*"
double-conversion = "3.3.1.*"
exceptiongroup = "1.3.0.*"
executing = "2.2.1.*"
fasteners = "0.19.*"
fastremap = "1.17.4.*"
ffmpeg = "8.0.0.*"
filelock = "3.19.1.*"
fill-voids = "2.1.1.*"
flexcache = "0.3.*"
flexparser = "0.4.*"
font-ttf-dejavu-sans-mono = "2.37.*"
font-ttf-inconsolata = "3.0.*"
font-ttf-source-code-pro = "2.38.*"
font-ttf-ubuntu = "0.83.*"
fontconfig = "2.15.0.*"
fonts-conda-ecosystem = "1.*"
fonts-conda-forge = "1.*"
fonttools = "4.59.2.*"
freeglut = "3.2.2.*"
freetype = "2.13.3.*"
freetype-py = "2.5.1.*"
fribidi = "1.0.10.*"
fsspec = "2025.9.0.*"
gdk-pixbuf = "2.42.12.*"
giflib = "5.2.2.*"
glslang = "15.4.0.*"
graphite2 = "1.3.14.*"
h2 = "4.3.0.*"
harfbuzz = "11.4.5.*"
hdf5 = "1.14.6.*"
heapdict = "1.0.1.*"
hpack = "4.1.0.*"
hsluv = "5.0.4.*"
humanfriendly = "10.0.*"
hyperframe = "6.1.0.*"
icu = "75.1.*"
idna = "3.10.*"
imagecodecs = "2025.3.30.*"
imageio = "2.37.0.*"
imagesize = "1.4.1.*"
imath = "3.2.1.*"
importlib-metadata = "8.7.0.*"
in-n-out = "0.2.1.*"
intel-openmp = "2025.2.0.*"
ipykernel = "6.30.1.*"
ipython = "8.37.0.*"
jasper = "4.2.8.*"
jedi = "0.19.2.*"
jinja2 = "3.1.6.*"
joblib = "1.5.2.*"
jsonschema = "4.25.1.*"
jsonschema-specifications = "2025.4.1.*"
jupyter_client = "8.6.3.*"
jupyter_core = "5.8.1.*"
jxrlib = "1.1.*"
khronos-opencl-icd-loader = "2024.10.24.*"
kiwisolver = "1.4.9.*"
krb5 = "1.21.3.*"
lame = "3.100.*"
lazy-loader = "0.4.*"
lazy_loader = "0.4.*"
lcms2 = "2.17.*"
lerc = "4.0.0.*"
libabseil = "20250512.1.*"
libaec = "1.1.4.*"
libarrow = "21.0.0.*"
libarrow-acero = "21.0.0.*"
libarrow-compute = "21.0.0.*"
libarrow-dataset = "21.0.0.*"
libarrow-substrait = "21.0.0.*"
libasprintf = "0.22.5.*"
libavif16 = "1.3.0.*"
libblas = "3.9.0.*"
libbrotlicommon = "1.1.0.*"
libbrotlidec = "1.1.0.*"
libbrotlienc = "1.1.0.*"
libcblas = "3.9.0.*"
libclang13 = "21.1.0.*"
libcrc32c = "1.1.2.*"
libcublas = "12.1.0.26.*"
libcublas-dev = "12.1.0.26.*"
libcufft = "11.0.2.4.*"
libcufft-dev = "11.0.2.4.*"
libcurand = "10.3.10.19.*"
libcurand-dev = "10.3.10.19.*"
libcurl = "8.14.1.*"
libcusolver = "11.4.4.55.*"
libcusolver-dev = "11.4.4.55.*"
libcusparse = "12.0.2.55.*"
libcusparse-dev = "12.0.2.55.*"
libdeflate = "1.24.*"
libevent = "2.1.12.*"
libexpat = "2.7.1.*"
libffi = "3.4.6.*"
libfreetype = "2.13.3.*"
libfreetype6 = "2.13.3.*"
libgettextpo = "0.22.5.*"
libglib = "2.84.3.*"
libgoogle-cloud = "2.39.0.*"
libgoogle-cloud-storage = "2.39.0.*"
libgrpc = "1.73.1.*"
libhwloc = "2.11.2.*"
libhwy = "1.3.0.*"
libiconv = "1.18.*"
libintl = "0.22.5.*"
libjpeg-turbo = "3.1.0.*"
libjxl = "0.11.1.*"
liblapack = "3.9.0.*"
liblapacke = "3.9.0.*"
liblzma = "5.8.1.*"
libnpp = "12.0.2.50.*"
libnpp-dev = "12.0.2.50.*"
libnvjitlink = "12.1.105.*"
libnvjitlink-dev = "12.1.105.*"
libnvjpeg = "12.1.1.14.*"
libnvjpeg-dev = "12.1.1.14.*"
libogg = "1.3.5.*"
libopencv = "4.12.0.*"
libopenvino = "2025.2.0.*"
libopenvino-auto-batch-plugin = "2025.2.0.*"
libopenvino-auto-plugin = "2025.2.0.*"
libopenvino-hetero-plugin = "2025.2.0.*"
libopenvino-intel-cpu-plugin = "2025.2.0.*"
libopenvino-intel-gpu-plugin = "2025.2.0.*"
libopenvino-ir-frontend = "2025.2.0.*"
libopenvino-onnx-frontend = "2025.2.0.*"
libopenvino-paddle-frontend = "2025.2.0.*"
libopenvino-pytorch-frontend = "2025.2.0.*"
libopenvino-tensorflow-frontend = "2025.2.0.*"
libopenvino-tensorflow-lite-frontend = "2025.2.0.*"
libopus = "1.5.2.*"
libparquet = "21.0.0.*"
libpng = "1.6.50.*"
libprotobuf = "6.31.1.*"
libre2-11 = "2025.7.22.*"
librsvg = "2.58.4.*"
libsodium = "1.0.20.*"
libsqlite = "3.50.4.*"
libssh2 = "1.11.1.*"
libthrift = "0.22.0.*"
libtiff = "4.7.0.*"
libusb = "1.0.29.*"
libutf8proc = "2.10.0.*"
libuv = "1.51.0.*"
libvorbis = "1.3.7.*"
libwebp = "1.6.0.*"
libwebp-base = "1.6.0.*"
libxcb = "1.16.*"
libxml2 = "2.13.8.*"
libxslt = "1.1.43.*"
libzlib = "1.3.1.*"
libzopfli = "1.0.3.*"
llvmlite = "0.44.0.*"
locket = "1.0.0.*"
logistro = "1.1.0.*"
lxml = "6.0.1.*"
lz4 = "4.4.4.*"
lz4-c = "1.10.0.*"
m2w64-gcc-libgfortran = "5.3.0.*"
m2w64-gcc-libs = "5.3.0.*"
m2w64-gcc-libs-core = "5.3.0.*"
m2w64-gmp = "6.1.0.*"
m2w64-libwinpthread-git = "5.0.0.4634.697f757.*"
magicgui = "0.10.1.*"
mako = "1.3.10.*"
markdown-it-py = "4.0.0.*"
markupsafe = "3.0.2.*"
matplotlib-base = "3.10.6.*"
matplotlib-inline = "0.1.7.*"
mdurl = "0.1.2.*"
mkl = "2023.1.0.*"
mpmath = "1.3.0.*"
msgpack-python = "1.1.1.*"
msys2-conda-epoch = "20160418.*"
munkres = "1.1.4.*"
napari = "0.6.4.*"
napari-base = "0.6.4.*"
napari-console = "0.1.3.*"
napari-plugin-engine = "0.2.0.*"
napari-plugin-manager = "0.1.6.*"
napari-svg = "0.2.1.*"
narwhals = "2.3.0.*"
natsort = "8.4.0.*"
nd2 = "0.10.3.*"
nest-asyncio = "1.6.0.*"
networkx = "3.4.2.*"
npe2 = "0.7.9.*"
numba = "0.61.2.*"
numcodecs = "0.13.1.*"
numpy = "2.2.6.*"
numpydoc = "1.9.0.*"
ome-types = "0.6.0.*"
onnx = "1.18.0.*"
onnxruntime = "1.22.0.*"
opencl-headers = "2025.6.13.*"
opencv = "4.12.0.*"
openexr = "3.3.5.*"
openh264 = "2.6.0.*"
openjpeg = "2.5.3.*"
openssl = "3.5.2.*"
orc = "2.2.0.*"
orjson = "3.11.3.*"
packaging = "25.0.*"
pandas = "2.3.2.*"
pango = "1.56.4.*"
parso = "0.8.5.*"
partd = "1.4.2.*"
partsegcore-compiled-backend = "0.15.13.*"
pcre2 = "10.45.*"
pickleshare = "0.7.5.*"
pillow = "10.4.0.*"
pims = "0.7.*"
pint = "0.24.4.*"
pip = "25.2.*"
pixman = "0.46.4.*"
platformdirs = "4.4.0.*"
plotly = "6.3.0.*"
pooch = "1.8.2.*"
prompt-toolkit = "3.0.52.*"
protobuf = "6.31.1.*"
psutil = "7.0.0.*"
psygnal = "0.14.1.*"
pthread-stubs = "0.4.*"
pthreads-win32 = "2.9.1.*"
pugixml = "1.15.*"
pure_eval = "0.2.3.*"
py-opencv = "4.12.0.*"
pyarrow = "21.0.0.*"
pyarrow-core = "21.0.0.*"
pyclesperanto-prototype = "0.24.4.*"
pycocotools = "2.0.10.*"
pyconify = "0.2.1.*"
pycparser = "2.22.*"
pydantic = "2.11.7.*"
pydantic-compat = "0.1.2.*"
pydantic-core = "2.33.2.*"
pydantic-extra-types = "2.10.5.*"
pygments = "2.19.2.*"
pyopencl = "2025.2.6.*"
pyopengl = "3.1.10.*"
pyparsing = "3.2.3.*"
pyproject_hooks = "1.2.0.*"
pyqtgraph = "0.13.7.*"
pyreadline3 = "3.5.4.*"
pyside6 = "6.9.2.*"
pysocks = "1.7.1.*"
python = "3.10.18.*"
python-build = "1.3.0.*"
python-dateutil = "2.9.0.post0.*"
python-flatbuffers = "25.2.10.*"
python-kaleido = "1.0.0.*"
python-tzdata = "2025.2.*"
python_abi = "3.10.*"
pytools = "2025.2.4.*"
pytorch = "2.5.0.*"
pytorch-cuda = "12.1.*"
pytorch-mutex = "1.0.*"
pytz = "2025.2.*"
pywavelets = "1.8.0.*"
pywin32 = "311.*"
pyyaml = "6.0.2.*"
pyzmq = "27.0.2.*"
qhull = "2020.2.*"
qt6-main = "6.9.2.*"
qtconsole-base = "5.6.1.*"
qtpy = "2.4.3.*"
rav1e = "0.7.1.*"
re2 = "2025.7.22.*"
referencing = "0.36.2.*"
requests = "2.32.5.*"
resource_backed_dask_array = "0.1.0.*"
rich = "14.1.0.*"
roifile = "2025.5.10.*"
rpds-py = "0.27.1.*"
ruff = "0.12.12.*"
scikit-image = "0.25.2.*"
scikit-learn = "1.7.1.*"
scipy = "1.15.2.*"
sdl2 = "2.32.54.*"
sdl3 = "3.2.22.*"
segment-anything = "1.0.1.*"
setuptools = "80.9.0.*"
shaderc = "2025.3.*"
shellingham = "1.5.4.*"
simplejson = "3.20.1.*"
siphash24 = "1.7.*"
six = "1.17.0.*"
slicerator = "1.1.0.*"
snappy = "1.2.2.*"
snowballstemmer = "3.0.1.*"
sortedcontainers = "2.4.0.*"
sphinx = "8.1.3.*"
sphinxcontrib-applehelp = "2.0.0.*"
sphinxcontrib-devhelp = "2.0.0.*"
sphinxcontrib-htmlhelp = "2.1.0.*"
sphinxcontrib-jsmath = "1.0.1.*"
sphinxcontrib-qthelp = "2.0.0.*"
sphinxcontrib-serializinghtml = "1.1.10.*"
spirv-tools = "2025.1.*"
stack_data = "0.6.3.*"
superqt = "0.7.6.*"
svt-av1 = "3.1.2.*"
tbb = "2021.13.0.*"
tblib = "3.1.0.*"
threadpoolctl = "3.6.0.*"
tifffile = "2025.5.10.*"
tk = "8.6.13.*"
tomli = "2.2.1.*"
tomli-w = "1.2.0.*"
toolz = "1.0.0.*"
toposort = "1.10.*"
tornado = "6.5.2.*"
tqdm = "4.67.1.*"
traitlets = "5.14.3.*"
transforms3d = "0.4.2.*"
typer = "0.17.3.*"
typer-slim = "0.17.3.*"
typer-slim-standard = "0.17.3.*"
typing-extensions = "4.15.0.*"
typing-inspection = "0.4.1.*"
typing_extensions = "4.15.0.*"
tzdata = "2025b.*"
ucrt = "10.0.26100.0.*"
unicodedata2 = "16.0.0.*"
untokenize = "0.1.1.*"
urllib3 = "2.5.0.*"
vc = "14.3.*"
vc14_runtime = "14.44.35208.*"
vcomp14 = "14.44.35208.*"
vispy = "0.15.2.*"
vs2015_runtime = "14.44.35208.*"
wcwidth = "0.2.13.*"
wheel = "0.45.1.*"
win_inet_pton = "1.1.0.*"
wrapt = "1.17.3.*"
x264 = "1!164.3095.*"
x265 = "3.5.*"
xorg-libxau = "1.0.11.*"
xorg-libxdmcp = "1.1.3.*"
xsdata = "24.3.1.*"
xyzservices = "2025.4.0.*"
yaml = "0.2.5.*"
zarr = "2.18.3.*"
zeromq = "4.3.5.*"
zfp = "1.0.1.*"
zict = "3.0.0.*"
zipp = "3.23.0.*"
zlib-ng = "2.2.5.*"
zstandard = "0.24.0.*"
zstd = "1.5.7.*"

[pypi-dependencies]
absl-py = "==2.3.1"
aiohappyeyeballs = "==2.6.1"
aiohttp = "==3.12.15"
aiosignal = "==1.4.0"
async-timeout = "==5.0.1"
configargparse = "==1.7.1"
crick = "==0.0.8"
csbdeep = "==0.8.1"
frozenlist = "==1.7.0"
gitdb = "==4.0.12"
gitpython = "==3.1.45"
grpcio = "==1.74.0"
lightning = "==2.5.5"
lightning-utilities = "==0.15.2"
markdown = "==3.9"
multidict = "==6.6.4"
propcache = "==0.3.2"
pydash = "==8.0.5"
pytorch-lightning = "==2.5.5"
sentry-sdk = "==2.37.0"
smmap = "==5.0.2"
spotiflow = "==0.5.8"
sympy = "==1.14.0"
tensorboard = "==2.20.0"
tensorboard-data-server = "==0.7.2"
torchmetrics = "==1.8.2"
torchvision = "==0.20.0"
wandb = "==0.21.3"
werkzeug = "==3.1.3"
yarl = "==1.20.1"
